Update bamboo-check.yml

diff --git a/.github/workflows/bamboo-check.yml b/.github/workflows/bamboo-check.yml
--- a/.github/workflows/bamboo-check.yml
+++ b/.github/workflows/bamboo-check.yml
@@ -11,11 +11,13 @@ jobs:
   check-for-update:
     name: 'Check for new version'
     runs-on: 'ubuntu-latest'
+
     outputs:
       update-available: ${{ steps.version-check.outputs.update-available }}
       compatible-version: ${{ steps.version-check.outputs.current-compatible-version }}
       bamboo-version: ${{ steps.version-check.outputs.latest-bamboo-version }}
       gh-issue-url: ${{ steps.create-issue.outputs.issue-url }}
+
     steps:
       - uses: actions/checkout@v3
 
@@ -35,10 +37,13 @@ jobs:
   create-issue:
     name: 'Create issue'
     runs-on: 'ubuntu-latest'
+
     needs: check-for-update
     if: ${{ needs.check-for-update.outputs.update-available }}
+
     outputs:
       gh-issue-url: ${{ steps.create-issue.outputs.issue-url }}
+
     steps:
       - uses: actions/checkout@v3
 
@@ -63,11 +68,14 @@ jobs:
   update-pom:
     name: 'Update POM.xml'
     runs-on: 'ubuntu-latest'
+
     needs: [check-for-update, create-issue]
     if: ${{ needs.create-issue.outputs.gh-issue-url != '' }}
+
     outputs:
       changes-committed: ${{ steps.commit-pom-update.outputs.changes-committed }}
       branch: ${{ steps.commit-pom-update.outputs.branch-name }}
+
     steps:
       - uses: actions/checkout@v3
 
@@ -81,25 +89,31 @@ jobs:
           git config --global user.email "integrationsfnmbot@octopus.com"
           git checkout -b $branchName
           
-          sed -i "s/\(^.*<bamboo.version>\).*\(<\/bamboo.version>.*$\)/\1$bambooVersion\2/g" pom.xml
-          sed -i "s/\(^.*<bamboo.data.version>\).*\(<\/bamboo.data.version>.*$\)/\1$bambooVersion\2/g" pom.xml
+          # Update the version in the <bamboo.version> and <bamboo.data.version> properties
+          sed "s/\(^.*<bamboo\(.data\)\?.version>\).*\(<\/bamboo\(.data\)\?.version>.*$\)/\1$bambooVersion\3/g" pom.xml
+
           git add pom.xml
-          git diff-index --quiet HEAD || (git commit -m "fix: update compatible bamboo version" && git push -u origin $branchName && echo "::set-output name=changes-committed::true")
-          
-          echo "::set-output name=branch-name::$branchName"
+          # if no changes were made, just silently exit
+          git diff-index --quiet HEAD || (git commit -m "fix: update compatible bamboo version" \
+            && git push -u origin $branchName \
+            && echo "::set-output name=changes-committed::true" \
+            && echo "::set-output name=branch-name::$branchName" \
+          )          
 
   create-pull-request:
     name: 'Create PR'
     runs-on: 'ubuntu-latest'
+
     needs: [check-for-update, create-issue, update-pom]
     if: ${{ needs.update-pom.outputs.changes-committed }}
+
     steps:
       - uses: actions/checkout@v3
 
       - name: 'Create PR to update Bamboo version in POM.xml'
         run: |
-          prTitle="Add compatibility for Bamboo version ${{ needs.check-for-update.outputs.bamboo-version }}"
-          prBody="Fixes ${{ needs.create-issue.outputs.gh-issue-url }}"
+          title="Add compatibility for Bamboo version ${{ needs.check-for-update.outputs.bamboo-version }}"
+          body="Fixes ${{ needs.create-issue.outputs.gh-issue-url }}"
           head="${{ needs.update-pom.outputs.branch }}"
           
-          gh pr create --title "$prTitle" --body "$prBody" --base "main" --head "$head" --reviewer "alfhenrik-test-2"
+          gh pr create --title "$title" --body "$body" --base "main" --head "$head" --reviewer "alfhenrik-test-2"
